package entities;
// Generated 13-feb-2018 10:36:59 by Hibernate Tools 4.3.1



/**
 * Fight generated by hbm2java
 */
public class Fight  implements java.io.Serializable {


     private Integer idfight;
     private Pokedex pokedexByWinner;
     private Pokedex pokedexByPokemon1;
     private Pokedex pokedexByPokemon2;

    public Fight() {
    }

	
    public Fight(Pokedex pokedexByPokemon1, Pokedex pokedexByPokemon2) {
        this.pokedexByPokemon1 = pokedexByPokemon1;
        this.pokedexByPokemon2 = pokedexByPokemon2;
    }
    public Fight(Pokedex pokedexByWinner, Pokedex pokedexByPokemon1, Pokedex pokedexByPokemon2) {
       this.pokedexByWinner = pokedexByWinner;
       this.pokedexByPokemon1 = pokedexByPokemon1;
       this.pokedexByPokemon2 = pokedexByPokemon2;
    }
   
    public Integer getIdfight() {
        return this.idfight;
    }
    
    public void setIdfight(Integer idfight) {
        this.idfight = idfight;
    }
    public Pokedex getPokedexByWinner() {
        return this.pokedexByWinner;
    }
    
    public void setPokedexByWinner(Pokedex pokedexByWinner) {
        this.pokedexByWinner = pokedexByWinner;
    }
    public Pokedex getPokedexByPokemon1() {
        return this.pokedexByPokemon1;
    }
    
    public void setPokedexByPokemon1(Pokedex pokedexByPokemon1) {
        this.pokedexByPokemon1 = pokedexByPokemon1;
    }
    public Pokedex getPokedexByPokemon2() {
        return this.pokedexByPokemon2;
    }
    
    public void setPokedexByPokemon2(Pokedex pokedexByPokemon2) {
        this.pokedexByPokemon2 = pokedexByPokemon2;
    }




}


