package entities;
// Generated 13-feb-2018 10:36:59 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Pokemon generated by hbm2java
 */
public class Pokemon  implements java.io.Serializable {


     private String name;
     private String type;
     private int pc;
     private int life;
     private String place;
     private Set pokedexes = new HashSet(0);

    public Pokemon() {
    }

	
    public Pokemon(String name, String type, int pc, int life, String place) {
        this.name = name;
        this.type = type;
        this.pc = pc;
        this.life = life;
        this.place = place;
    }
    public Pokemon(String name, String type, int pc, int life, String place, Set pokedexes) {
       this.name = name;
       this.type = type;
       this.pc = pc;
       this.life = life;
       this.place = place;
       this.pokedexes = pokedexes;
    }
   
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public int getPc() {
        return this.pc;
    }
    
    public void setPc(int pc) {
        this.pc = pc;
    }
    public int getLife() {
        return this.life;
    }
    
    public void setLife(int life) {
        this.life = life;
    }
    public String getPlace() {
        return this.place;
    }
    
    public void setPlace(String place) {
        this.place = place;
    }
    public Set getPokedexes() {
        return this.pokedexes;
    }
    
    public void setPokedexes(Set pokedexes) {
        this.pokedexes = pokedexes;
    }




}


