package entities;
// Generated 13-feb-2018 10:36:59 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pokedex generated by hbm2java
 */
public class Pokedex  implements java.io.Serializable {


     private Integer idpokedex;
     private Pokemon pokemon;
     private User user;
     private Date date;
     private int pc;
     private int lifemax;
     private int lifecurrent;
     private Set fightsForWinner = new HashSet(0);
     private Set fightsForPokemon1 = new HashSet(0);
     private Set fightsForPokemon2 = new HashSet(0);

    public Pokedex() {
    }

	
    public Pokedex(Pokemon pokemon, User user, Date date, int pc, int lifemax, int lifecurrent) {
        this.pokemon = pokemon;
        this.user = user;
        this.date = date;
        this.pc = pc;
        this.lifemax = lifemax;
        this.lifecurrent = lifecurrent;
    }
    public Pokedex(Pokemon pokemon, User user, Date date, int pc, int lifemax, int lifecurrent, Set fightsForWinner, Set fightsForPokemon1, Set fightsForPokemon2) {
       this.pokemon = pokemon;
       this.user = user;
       this.date = date;
       this.pc = pc;
       this.lifemax = lifemax;
       this.lifecurrent = lifecurrent;
       this.fightsForWinner = fightsForWinner;
       this.fightsForPokemon1 = fightsForPokemon1;
       this.fightsForPokemon2 = fightsForPokemon2;
    }
   
    public Integer getIdpokedex() {
        return this.idpokedex;
    }
    
    public void setIdpokedex(Integer idpokedex) {
        this.idpokedex = idpokedex;
    }
    public Pokemon getPokemon() {
        return this.pokemon;
    }
    
    public void setPokemon(Pokemon pokemon) {
        this.pokemon = pokemon;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public int getPc() {
        return this.pc;
    }
    
    public void setPc(int pc) {
        this.pc = pc;
    }
    public int getLifemax() {
        return this.lifemax;
    }
    
    public void setLifemax(int lifemax) {
        this.lifemax = lifemax;
    }
    public int getLifecurrent() {
        return this.lifecurrent;
    }
    
    public void setLifecurrent(int lifecurrent) {
        this.lifecurrent = lifecurrent;
    }
    public Set getFightsForWinner() {
        return this.fightsForWinner;
    }
    
    public void setFightsForWinner(Set fightsForWinner) {
        this.fightsForWinner = fightsForWinner;
    }
    public Set getFightsForPokemon1() {
        return this.fightsForPokemon1;
    }
    
    public void setFightsForPokemon1(Set fightsForPokemon1) {
        this.fightsForPokemon1 = fightsForPokemon1;
    }
    public Set getFightsForPokemon2() {
        return this.fightsForPokemon2;
    }
    
    public void setFightsForPokemon2(Set fightsForPokemon2) {
        this.fightsForPokemon2 = fightsForPokemon2;
    }




}


