package entities;
// Generated 13-feb-2018 10:36:59 by Hibernate Tools 4.3.1



/**
 * Pokeparada generated by hbm2java
 */
public class Pokeparada  implements java.io.Serializable {


     private String name;
     private String place;
     private int pokeballs;
     private int potions;

    public Pokeparada() {
    }

    public Pokeparada(String name, String place, int pokeballs, int potions) {
       this.name = name;
       this.place = place;
       this.pokeballs = pokeballs;
       this.potions = potions;
    }
   
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getPlace() {
        return this.place;
    }
    
    public void setPlace(String place) {
        this.place = place;
    }
    public int getPokeballs() {
        return this.pokeballs;
    }
    
    public void setPokeballs(int pokeballs) {
        this.pokeballs = pokeballs;
    }
    public int getPotions() {
        return this.potions;
    }
    
    public void setPotions(int potions) {
        this.potions = potions;
    }




}


