package entities;
// Generated 13-feb-2018 10:36:59 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private String username;
     private String password;
     private int pokeballs;
     private int potions;
     private int level;
     private String place;
     private int pokecoins;
     private int points;
     private Set pokedexes = new HashSet(0);

    public User() {
    }

	
    public User(String username, String password, int pokeballs, int potions, int level, String place, int pokecoins, int points) {
        this.username = username;
        this.password = password;
        this.pokeballs = pokeballs;
        this.potions = potions;
        this.level = level;
        this.place = place;
        this.pokecoins = pokecoins;
        this.points = points;
    }
    public User(String username, String password, int pokeballs, int potions, int level, String place, int pokecoins, int points, Set pokedexes) {
       this.username = username;
       this.password = password;
       this.pokeballs = pokeballs;
       this.potions = potions;
       this.level = level;
       this.place = place;
       this.pokecoins = pokecoins;
       this.points = points;
       this.pokedexes = pokedexes;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public int getPokeballs() {
        return this.pokeballs;
    }
    
    public void setPokeballs(int pokeballs) {
        this.pokeballs = pokeballs;
    }
    public int getPotions() {
        return this.potions;
    }
    
    public void setPotions(int potions) {
        this.potions = potions;
    }
    public int getLevel() {
        return this.level;
    }
    
    public void setLevel(int level) {
        this.level = level;
    }
    public String getPlace() {
        return this.place;
    }
    
    public void setPlace(String place) {
        this.place = place;
    }
    public int getPokecoins() {
        return this.pokecoins;
    }
    
    public void setPokecoins(int pokecoins) {
        this.pokecoins = pokecoins;
    }
    public int getPoints() {
        return this.points;
    }
    
    public void setPoints(int points) {
        this.points = points;
    }
    public Set getPokedexes() {
        return this.pokedexes;
    }
    
    public void setPokedexes(Set pokedexes) {
        this.pokedexes = pokedexes;
    }




}


